args <- commandArgs(trailingOnly=TRUE)
root <- normalizePath(args[1], winslash="/", mustWork=TRUE)
suppressPackageStartupMessages(library(edgeR))
x <- read.delim(gzfile(file.path(root,"cache/bulk_counts.tsv.gz")),check.names=FALSE,row.names=1)
keep <- rowSums(x>=10)>=2
y <- DGEList(counts=x[keep,,drop=FALSE])
y <- calcNormFactors(y,method="TMM")
logcpm <- log2(cpm(y,log=FALSE)+1)
plain <- log2(sweep(as.matrix(x[keep,,drop=FALSE]),2,colSums(x[keep,,drop=FALSE]),"/")*1e6+1)
write.table(data.frame(gene_id=rownames(logcpm),logcpm,check.names=FALSE),gzfile(file.path(root,"cache/bulk_tmm_log2cpm.tsv.gz")),sep="\t",quote=FALSE,row.names=FALSE)
write.table(data.frame(gene_id=rownames(plain),plain,check.names=FALSE),gzfile(file.path(root,"cache/bulk_total_log2cpm.tsv.gz")),sep="\t",quote=FALSE,row.names=FALSE)
out <- data.frame(sample=rownames(y$samples),library_size=y$samples$lib.size,tmm_factor=y$samples$norm.factors,effective_library_size=y$samples$lib.size*y$samples$norm.factors,retained_genes=sum(keep))
write.table(out,file.path(root,"tables/exploratory_v1/bulk_normalization.tsv"),sep="\t",quote=FALSE,row.names=FALSE)
writeLines(capture.output(sessionInfo()),file.path(root,"reports/R_session.txt"))
cat("TMM normalized",sum(keep),"of",nrow(x),"genes across",ncol(x),"libraries. No DE model fitted.\n")
